apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: examiner
  namespace: helm
spec:
  chart:
    spec:
      chart: application
      version: "~1"
      sourceRef:
        kind: HelmRepository
        name: chart-repo
        namespace: helm
      interval: 60m
  interval: 1m
  values:
    image:
      repository: quay.io/heubeck/examiner
      tag: latest
    monitoring:
      serviceMonitor: true
    configuration:
      ECHO_VALUE: ⛈ Helm Canaries r0ck, hell yeah! 🤘
      SERVER_ERROR_RATE: 3
      REQUEST_DELAY: 50..250
    gatewayApi:
      enabled: true
      pathPrefix: /examine-helm
      gatewayRef:
        name: http-gateway
        namespace: default
    canary:
      enabled: true
      analysis:
        interval: 60s
        threshold: 2
        maxWeight: 100
        stepWeight: 20
        stepWeightPromotion: 35
        metrics:
          - name: server-success-rate
            templateRef:
              name: server-success-rate
              namespace: flux-system
            thresholdRange:
              min: 90
            interval: 1m
          - name: request-latency-p99
            templateRef:
              name: request-latency-p99
              namespace: flux-system
            thresholdRange:
              max: 500
            interval: 1m
