---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flux-pod-monitor.yaml
- flux-service-monitor.yaml
- cilium-service-monitors.yaml
configMapGenerator:
  - name: flux-grafana-dashboards
    namespace: monitoring
    files:
      - grafana-dashboards/control-plane.json
      - grafana-dashboards/cluster.json
    options:
      labels:
        grafana_dashboard: "1"
