---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system
resources:
  # see https://github.com/metallb/metallb/releases
  - github.com/metallb/metallb/config/native?ref=v0.14.3
