---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: weave-charts
  namespace: dashboard
spec:
  interval: 1h0m0s
  type: oci
  url: oci://ghcr.io/weaveworks/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wego
  namespace: dashboard
spec:
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: weave-charts
  interval: 1h0m0s
  values:
    adminUser:
      create: true
      username: admin
      # password: admin
      passwordHash: $2a$10$ZGFJf47srKNbwhjGK1C/YuyH3WnyBp.6yA3dakpgqSSjSAeRxZRCq
    additionalArgs:
      - "--route-prefix=/wego"
