---
# https://github.com/fluxcd/flagger/blob/main/pkg/apis/flagger/v1beta1/canary.go
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: examiner
  namespace: plain
spec:
  analysis:

    # schedule interval (default 60s)
    interval: 60s

    # max traffic percentage routed to canary
    # percentage (0-100)
    maxWeight: 100

    # Incremental traffic weight step for analysis phase
    # percentage (0-100)
    stepWeight: 20
    # or: Predefined traffic weight steps for analysis phase
    # stepWeights: [1, 2, 10, 80]

    # Incremental traffic weight step for promotion phase
    # percentage (0-100)
    stepWeightPromotion: 35

    # Max number of failed checks before the canary is terminated and rolled back
    threshold: 2

    alerts: []
    webhooks: []
    metrics:
    - interval: 1m
      name: server-success-rate
      templateRef:
        name: server-success-rate
        namespace: flux-system
      thresholdRange:
        min: 90
    - interval: 1m
      name: request-latency-p99
      templateRef:
        name: request-latency-p99
        namespace: flux-system
      thresholdRange:
        max: 500

  progressDeadlineSeconds: 600
  autoscalerRef:
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    name: examiner
  provider: gatewayapi:v1
  service:
    gatewayRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: http-gateway
      namespace: default
    match:
    - uri:
        prefix: /examine-plain
    rewrite:
      uri: /examine
      type: ReplacePrefixMatch
    port: 80
    targetPort: 8080
    timeout: 120s
  skipAnalysis: false
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: examiner
