---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: examiner
  namespace: plain
spec:
  minReplicas: 1
  maxReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: examiner
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 100
