---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml
- serviceaccount.yaml
- deployment.yaml
- service.yaml
#- canary.yaml
# HttpRoute is created by Flagger if Canary is configured
- route.yaml
